[package]
name = "trezoa-sbpf"
version = "0.14.0"
description = "Virtual machine and JIT compiler for eBPF programs"
authors = ["Trezoa-team Maintainers <maintainers@trezoa.xyz>"]
repository = "https://github.com/trezoa-xyz/sbpf"
homepage = "https://trezoa.com/"
keywords = ["BPF", "eBPF", "interpreter", "JIT", "filtering"]
license = "Apache-2.0"
edition = "2018"

include = [
    "src/**",
    "examples/**",
    "tests/**",
    "benches/**",
    "LICENSE*",
    "Cargo.toml",
]

[dependencies]
arbitrary = { version = "1.0", optional = true, features = ["derive"] }
byteorder = "1.2"
combine = "3.8.1"
gdbstub = { version = "0.6.2", optional = true }
hash32 = "0.3.1"
log = "0.4.2"
rand = { version = "0.8.5", features = ["small_rng"], optional = true }
rustc-demangle = "0.1"
shuttle = { version = "0.7.1", optional = true }
thiserror = "2.0.9"

[target.'cfg(windows)'.dependencies]
winapi = { version = "0.3", features = ["memoryapi", "sysinfoapi", "winnt", "errhandlingapi"], optional = true }

[target.'cfg(not(windows))'.dependencies]
libc = { version = "0.2", optional = true }

[features]
default = ["jit"]
jit = ["dep:libc", "dep:winapi", "dep:rand"]
jit-enable-host-stack-frames = ["jit"]
fuzzer-not-safe-for-production = ["arbitrary"]
debugger = ["dep:gdbstub"]
shuttle-test = ["dep:shuttle"]

[dev-dependencies]
elf = "0.0.10"
json = "0.12"
test_utils = { path = "test_utils/" }
