[package]
name = "test_utils"
version = "0.14.0"
authors = ["Trezoa-team Maintainers <maintainers@trezoa.xyz>"]
edition = "2018"
publish = false

[dependencies]
libc = "0.2"
trezoa-sbpf = { path = "../" }
